# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
# Stacks detected: cicd:github-actions:.github/workflows
version: 2.1

executors:
  pactfoundation:
    docker:
      - image: pactfoundation/pact-cli
        environment:
          PACT_BROKER_BASE_URL: https://beso.pactflow.io
          PACT_BROKER_TOKEN: zsfJLRiOlESCkhIqhv7Ltg

jobs:
  test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0
    environment:
      PACKAGE_VERSION: 1.3.<< pipeline.number >>
    steps:
      - checkout
      - run:
          name: Test
          command: |
            dotnet test tests
      - run:
          name: List files and folders in current directory
          command: |
            ls -l
      - persist_to_workspace:
          root: ./
          paths:
            - "pacts"

  pact-publish:
    executor: pactfoundation
    steps:
      - attach_workspace:
          at: ./tmp
      - run:
          name: List files and folders in current directory
          command: |
            ls ./tmp/pacts
      - run:
          name: publish
          command: |
            PACT_CLI="pact broker publish ./tmp/pacts --auto-detect-version-properties"
            ${PACT_CLI}

  pact-can-i-deploy:
    executor: pactfoundation
    steps:
      - run:
          name: canideploy
          command: |
            PACT_CLI="pact broker can-i-deploy --pacticipant pactflow-example-consumer-dotnet --version ${CIRCLE_SHA1} --to-environment production"
            ${PACT_CLI}  
  pact-deploy:
    executor: pactfoundation
    steps:
      - run:
          name: deploy
          command: |
            PACT_CLI="pact broker record_deployment --pacticipant pactflow-example-consumer-dotnet --version ${CIRCLE_SHA1} --environment production"
            ${PACT_CLI}

workflows:
  example:
    jobs:
      - test:
          name: tests
      - pact-publish:
          name: publish-pact
          requires:
            - tests
      - pact-can-i-deploy:
          name: pact-can-i-deploy
          requires:
            - publish-pact
      - pact-deploy:
          name: pact-deploy
          requires:
            - pact-can-i-deploy
